version: '3.9'

services:
  deployment-manager:
    build: .
    container_name: deployment-manager
    ports:
      - "8005:8005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
      - ./.env:/app/.env
      - /Users/uditkhandelwal/Documents/testing:/app/docker/deployments
    environment:
      - ENV=development
      - FLASK_ENV=development
      - WORKSPACE_BASE_DIR=/app/workspaces
      - LOGS_DIR=/app/logs
      - DOCKER_BASE_DIR=/app/docker/deployments
      - DATABASE=deployment_manager_test
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - backend-network
  
  redis:
    image: redis:alpine
    container_name: deploy-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - backend-network

volumes:
  redis_data:

networks:
  backend-network: