version: '3.9'

services:
  deployment-manager:
    build: .
    container_name: deployment-manager
    # Removed ports mapping to prevent direct host:port access
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/azureuser/service/logs:/app/logs
      - /home/azureuser/remote:/app/watcher
      - /home/azureuser/ws/.env:/app/.env
      - /home/azureuser/deployments:/app/docker/deployments
      - /home/azureuser/assets/traefik:/app/traefik
    environment:
      - ENV=production
      - FLASK_ENV=production
      - WORKSPACE_BASE_DIR=/app/workspaces
      - LOGS_DIR=/app/logs
      - DOCKER_BASE_DIR=/app/docker/deployments
      - BASE_VOLUME_DIR_MAP=/app/docker/deployments:/home/azureuser/deployments
      - APP_BUILDER_URL=https://appbuilder.synergiqai.com
      - FLUENTD_HOST=10.1.0.4
      - FLUENTD_PORT=24224
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.deployment-manager.rule=Host(`apps.synergiqai.com`)"
      - "traefik.http.routers.deployment-manager.entrypoints=websecure"
      - "traefik.http.routers.deployment-manager.tls=true"
      - "traefik.http.routers.deployment-manager.tls.certresolver=letsencrypt"
      - "traefik.http.services.deployment-manager.loadbalancer.server.port=8005"
    networks:
      - backend-network
      - traefik-public
    depends_on:
      redis:
        condition: service_started
      fluentd:
        condition: service_healthy
    # Fluentd logging configuration
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.1.0.4:24224
        tag: internal.production.deployment-manager
  
  redis:
    image: redis:alpine
    container_name: deploy-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - backend-network

  fluentd:
    image: fluent/fluentd:v1.16-1
    platform: linux/amd64
    container_name: fluentd-prod
    healthcheck:
      test: ["CMD", "nc", "-z", "10.1.0.4", "24224"]
      interval: 10s      # Less frequent checks (every 10s instead of 5s)
      timeout: 3s
      retries: 5         # Fewer retries (3 instead of 6)
      start_period: 15s  # Longer initial wait
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - /home/azureuser/ws/fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - /home/azureuser/remote:/fluentd/log
      - /home/azureuser/service:/fluentd/internal/log
    networks:
      - backend-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  traefik-public:
    external: true
  backend-network: