version: '3.9'

services:
  deployment-manager:
    build: .
    container_name: deployment-manager
    ports:
      - "8005:8005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
      - ./.env:/app/.env
      - /Users/uditkhandelwal/Documents/testing:/app/docker/deployments
    environment:
      - ENV=development
      - FLASK_ENV=development
      - WORKSPACE_BASE_DIR=/app/workspaces
      - LOGS_DIR=/app/logs
      - DOCKER_BASE_DIR=/app/docker/deployments
      - BASE_VOLUME_DIR_MAP=/app/docker/deployments:/Users/uditkhandelwal/Documents/testing
      - DATABASE=deployment_manager_test
      - APP_BUILDER_URL=http://host.docker.internal:8002
      - FLUENTD_HOST=host.docker.internal
      - FLUENTD_PORT=24224
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - backend-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: internal.dev.deployment-manager
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: deploy-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - backend-network

  fluentd:
    image: fluent/fluentd:v1.16-1
    platform: linux/amd64
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/fluentd/log
      - ./logs:/fluentd/internal/log
    networks:
      - backend-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  backend-network: