version: '3.9'

services:
  deployment-manager:
    build: .
    container_name: deployment-manager
    # Removed ports mapping to prevent direct host:port access
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/azureuser/service/logs:/app/logs
      - /home/azureuser/ws/.env:/app/.env
      - /home/azureuser/deployments:/app/docker/deployments
    environment:
      - ENV=production
      - FLASK_ENV=production
      - WORKSPACE_BASE_DIR=/app/workspaces
      - LOGS_DIR=/app/logs
      - DOCKER_BASE_DIR=/app/docker/deployments
      - BASE_VOLUME_DIR_MAP=/app/docker/deployments:/home/azureuser/deployments
      - APP_BUILDER_URL=https://appbuilder.synergiqai.com
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deployment-manager.rule=Host(`apps.synergiqai.com`)"
      - "traefik.http.routers.deployment-manager.entrypoints=websecure"
      - "traefik.http.routers.deployment-manager.tls=true"
      - "traefik.http.routers.deployment-manager.tls.certresolver=letsencrypt"
      - "traefik.http.services.deployment-manager.loadbalancer.server.port=8005"
    networks:
      - backend-network
      - traefik-public
  
  redis:
    image: redis:alpine
    container_name: deploy-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - backend-network

volumes:
  redis_data:

networks:
  traefik-public:
    external: true
  backend-network: